version: "3.9"

services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: sgst_user
      POSTGRES_PASSWORD: sgst_password
      POSTGRES_DB: sgst_db
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: always

    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sgst_user -d sgst_db" ]
      interval: 2s
      timeout: 5s
      retries: 10

  node:
    image: node
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"

  web:
    image: nginx
    depends_on:
      - node
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  pg-data:

