version: "3.9"

services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: sgst_user
      POSTGRES_PASSWORD: sgst_password
      POSTGRES_DB: sgst_db
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always

    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sgst_user -d sgst_db" ]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  pg-data:
